### PR TITLE
Fix (small) spacing and typographic issues

### PR DESCRIPTION
**Pull request by liberforce**
Use 'png' instead of 'PNG'.

### CODE REVIEW

**Comment by zoic21** [comment]
Sorry asciidoctor is case sensitive so if we change PNG to png we need to rename all doc image

**Comment by liberforce** [comment]
I don't see the point. All *.PNG files have been renamed to *.png in my patch.

**Comment by liberforce** [comment]
Thanks! Since then I saw that the translation is in fact handled in transifex. Do you have contribution guidelines somewhere? For example I don't know which files are used as the pivot language for translation. The ones under id_ID? fr_FR?

**Comment by liberforce** [comment]
Well, seems id_ID is for indonesian...

**Pull request merged**
